version: '3'

services:
  nginx:
    #build: ./nginx
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    # - "443:443"
    depends_on:
     - wordpress
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./data/html:/var/www/html
    networks:
       - backend
    
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:  mysql_root_pass
      MYSQL_DATABASE: db_name
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_pass
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - backend

  wordpress:
    build: ./wordpress
    #image: wordpress:php7.3-fpm-alpine
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    volumes:
      - ./data/html:/var/www/html
    networks:
      - backend
    environment:
      WORDPRESS_DB_HOST:  mariadb
      MYSQL_ROOT_PASSWORD:  mysql_root_pass
      WORDPRESS_DB_NAME:  db_name
      WORDPRESS_DB_USER:  user_name
      WORDPRESS_USER: reaster
      WORDPRESS_PASSWORD:  12345678
      WORDPRESS_DB_PASSWORD:  user_pass
      WORDPRESS_TABLE_PREFIX: wp_
      TITLE: mysebsite
      URL: http://mywebsite.com
      ADMIN_USER: admin
      ADMIN_PASSWORD: admin
      ADMIN_EMAIL: admin@admin.fr


# volumes:
#   mdb:
#     driver: local
#     driver_opts:
#       type: "none"
#       o: "bind"
#       device: "/Users/reaster/42-Work/inception/data/mysql"
#       #devile: "${HOME}/data/html"

#   wordpress:
#     driver: local
#     driver_opts:
#       type: "none"
#       o: "bind"
#       devile: "/Users/reaster/42-Work/inception/data/html"
#       #device: "${HOME}/data/html"

networks:
  backend: