version: '3'

services:
  nginx:
    build: ./nginx
    #image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
     - wordpress
    restart: always
    volumes:
      #- ./nginx:/etc/nginx/conf.d
      - wp_vol:/var/www/html
    networks:
       - backend
    
  mariadb:
    build : ./mariadb
    #image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:  mysql_root_pass
      MYSQL_DATABASE: db_name
      MYSQL_ADMIN: macron
      MYSQL_ADMIN_PASSWORD: demission
      MYSQL_USER: earnaud
      MYSQL_PASSWORD: 1234
    volumes:
      - db_vol:/var/lib/mysql
    networks:
      - backend

  wordpress:
    build: ./wordpress
    #image: wordpress:php7.3-fpm-alpine
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    volumes:
      - wp_vol:/var/www/html
    networks:
      - backend
    environment:
      WORDPRESS_DB_HOST:  mariadb
      MYSQL_ROOT_PASSWORD:  mysql_root_pass
      WORDPRESS_DB_NAME:  db_name
      WORDPRESS_DB_USER:  earnaud
      WORDPRESS_USER: reaster
      WORDPRESS_PASSWORD:  12345678
      WORDPRESS_DB_PASSWORD:  1234
      WORDPRESS_TABLE_PREFIX: wp_
      TITLE: mysebsite
      URL: http://mywebsite.com
      ADMIN_USER: admin
      ADMIN_PASSWORD: admin
      ADMIN_EMAIL: admin@admin.fr


volumes:
    wp_vol:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: 'data/html'
    db_vol:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: 'data/mysql'

networks:
  backend: