version: '3'

services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
     - wordpress
    restart: always
    volumes:
      - wp_vol:/var/www/html
    networks:
       - backend
    
  mariadb:
    build : ./mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:  mysql_root_pass
      MYSQL_DATABASE: db_name
      MYSQL_USER: macron
      MYSQL_PASSWORD: demission
    volumes:
      - db_vol:/var/lib/mysql
    networks:
      - backend

  wordpress:
    build: ./wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    volumes:
      - wp_vol:/var/www/html
    networks:
      - backend
    environment:
      WORDPRESS_DB_HOST:  mariadb
      MYSQL_ROOT_PASSWORD:  mysql_root_pass
      WORDPRESS_DB_NAME:  db_name
      WORDPRESS_DB_USER:  macron
      WORDPRESS_DB_PASSWORD:  demission
      WORDPRESS_TABLE_PREFIX: wp_


volumes:
    wp_vol:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/user42/data/html'
    db_vol:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/user42/data/mysql'

networks:
  backend:
